import type { Tool, WhatsNew } from "./sheets";

export const MOCK_TOOLS: Tool[] = [
  {
    name: "Cursor",
    category: "Building & Deployment",
    what_it_does: "AI-powered code editor built on VS Code with deep integration for code generation, refactoring, and chat-based debugging.",
    my_use_case: "Primary IDE for all development work. Using it to build and iterate on this site and client projects.",
    free_tier: "Limited completions",
    cost: "$20/mo Pro",
    status: "in_stack",
    credibility: "Backed by a16z, used by thousands of devs daily",
    quick_notes: "Tab completions are addictive. Multi-file edits still hit-or-miss.",
    key_integrations: "VS Code, GitHub, Vercel, Claude, GPT-4",
    verdict: "The best AI code editor right now. Not perfect — multi-file refactors can hallucinate — but the speed boost is real. Worth every penny if you write code daily.",
    url: "https://cursor.sh",
  },
  {
    name: "Notion",
    category: "Productivity & Voice",
    what_it_does: "All-in-one workspace for notes, docs, wikis, project management, and databases with AI assistance.",
    my_use_case: "Central hub for project briefs, client docs, and content planning. Replaced Google Docs entirely.",
    free_tier: "Generous free plan",
    cost: "$10/mo Plus",
    status: "in_stack",
    credibility: "35M+ users, dominant in startup/creator space",
    quick_notes: "AI summaries are useful. Database views are powerful once you learn them.",
    key_integrations: "Slack, Google Drive, Figma, Zapier, Calendar",
    verdict: "Still the best all-rounder for knowledge work. The AI features are a nice add but not the reason to use it — the flexibility of databases and views is.",
    url: "https://notion.so",
  },
  {
    name: "Midjourney",
    category: "Design & Image",
    what_it_does: "AI image generation tool accessed via Discord or web app. Creates photorealistic and artistic images from text prompts.",
    my_use_case: "Hero images, social media assets, and concept art for client pitches.",
    free_tier: "None",
    cost: "$10/mo Basic",
    status: "trialling",
    credibility: "Industry leader in aesthetic quality, 16M+ users",
    quick_notes: "V6 is a massive leap. Web editor still limited vs Discord workflow.",
    key_integrations: "Discord, Photoshop (plugin), Canva",
    verdict: "Produces the most visually striking images of any AI tool. The Discord-first UX is divisive but the results speak for themselves. Worth trialling for any visual work.",
    url: "https://midjourney.com",
  },
  {
    name: "Perplexity",
    category: "Research & Knowledge",
    what_it_does: "AI-powered search engine that provides sourced answers with citations, combining web search with LLM reasoning.",
    my_use_case: "Quick research, fact-checking claims, and exploring topics before deep dives.",
    free_tier: "5 Pro searches/day",
    cost: "$20/mo Pro",
    status: "queued",
    credibility: "Backed by Bezos, Nvidia. Growing fast as Google Search alternative",
    quick_notes: "Citations are the killer feature. Spaces for team research are promising.",
    key_integrations: "Chrome extension, Slack, API access",
    verdict: "The best AI search tool available. Citations make it trustworthy in a way ChatGPT isn't. Pro is worth it if you do any kind of research regularly.",
    url: "https://perplexity.ai",
  },
];

export const MOCK_WHATS_NEW: WhatsNew[] = [
  {
    name: "Claude 4 Opus Released",
    developer: "Anthropic",
    launched: "March 2026",
    what_it_is: "Anthropic's most capable model yet. Significantly improved reasoning, coding, and instruction following. Extended context window to 500K tokens.",
    key_integrations: "API, Cursor, Amazon Bedrock, Google Cloud",
    watch_out_for: "Pricing is steep at $75/MTok output. Rate limits tight at launch.",
    relevance: "Major upgrade for anyone using Claude in their stack. The coding improvements alone justify switching.",
    status: "Foundation Model",
    verdict: "A genuine leap. The reasoning improvements are immediately noticeable — fewer hallucinations, better at following complex multi-step instructions. The price is the only downside.",
    relevance_level: "high",
    batch: "March 2026",
  },
  {
    name: "Figma AI Redesign",
    developer: "Figma",
    launched: "March 2026",
    what_it_is: "Figma ships a ground-up AI redesign: generate full layouts from prompts, auto-responsive components, and a visual diff tool for design reviews.",
    key_integrations: "Figma, Storybook, GitHub, Linear",
    watch_out_for: "Only available on Organization plan. Generated designs need heavy editing.",
    relevance: "Could change how design-to-dev handoff works. Worth watching closely.",
    status: "Design Tool",
    verdict: "Impressive demo, mixed reality. The auto-responsive feature is genuinely useful. The prompt-to-layout needs another iteration before it's production-ready.",
    relevance_level: "worth_knowing",
    batch: "March 2026",
  },
  {
    name: "Replit Agent v3",
    developer: "Replit",
    launched: "February 2026",
    what_it_is: "Major update to Replit's AI agent. Can now deploy full-stack apps, manage databases, and handle multi-file refactors autonomously.",
    key_integrations: "Replit, PostgreSQL, GCP, Stripe",
    watch_out_for: "Still struggles with complex state management. Costs add up on Hacker plan.",
    relevance: "Direct competitor to Lovable and Cursor for no-code/low-code builders.",
    status: "Dev Platform",
    verdict: "Getting better fast but still behind Cursor for experienced devs. The deployment story is strong though — zero-config deploys are genuinely effortless.",
    relevance_level: "watch",
    batch: "February 2026",
  },
  {
    name: "Arc Browser Sunset",
    developer: "The Browser Company",
    launched: "March 2026",
    what_it_is: "The Browser Company announces Arc will enter maintenance mode as they pivot to a new AI-native browser project codenamed 'Dia'.",
    key_integrations: "N/A",
    watch_out_for: "Existing Arc users should plan migration. Bookmarks/spaces export available.",
    relevance: "Cautionary tale about VC-funded consumer software. If you built workflows around Arc, start migrating.",
    status: "Browser",
    verdict: "Disappointing but not surprising. Arc was beautifully designed but never hit mainstream adoption. The pivot to AI-native browsing is a bet — unclear if it'll pay off.",
    relevance_level: "know_about",
    batch: "March 2026",
  },
];
